name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup SSH and Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.SSH_PORT || '10022' }}  # デフォルト値を設定
        run: |
          # デバッグ情報
          echo "Connecting to $USER@$HOST:$PORT"
          
          # ポート番号の確認
          if [ -z "$PORT" ]; then
            echo "Error: PORT is not set!"
            exit 1
          fi
          
          # SSH設定
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          
          # 秘密鍵を書き出す
          echo "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          
          # 鍵の確認
          echo "Key info:"
          ssh-keygen -y -f ~/.ssh/deploy_key > /dev/null && echo "Key is valid" || echo "Key is invalid"
          
          # known_hosts設定
          ssh-keyscan -p $PORT -H $HOST >> ~/.ssh/known_hosts 2>/dev/null
          
          # SSH接続テスト
          echo "Testing SSH connection..."
          ssh -i ~/.ssh/deploy_key -p $PORT -o ConnectTimeout=10 $USER@$HOST "echo 'Connected successfully'"
          
          # デプロイ実行
          echo "Starting deployment..."
          ssh -i ~/.ssh/deploy_key -p $PORT $USER@$HOST << 'EOF'
            set -e
            THEME_DIR="/home/wp629555/refine-jewelry-reform.com/public_html/wp-content/themes/refine-jewelry-reform"
            
            # ディレクトリが存在しない場合は作成
            mkdir -p "$THEME_DIR"
            cd "$THEME_DIR"
            
            # Gitリポジトリが存在するかチェック
            if [ ! -d ".git" ]; then
              echo "Initializing new repository..."
              # 既存ファイルがある場合は一旦退避
              if [ "$(ls -A)" ]; then
                echo "Backing up existing files..."
                mkdir -p ../refine-jewelry-reform-backup
                mv * ../refine-jewelry-reform-backup/ 2>/dev/null || true
              fi
              
              # 方法1: wgetまたはcurlでアーカイブをダウンロード
              echo "Downloading repository archive..."
              if command -v wget &> /dev/null; then
                wget -q https://github.com/harmonic-society/refine-jewelry-reform/archive/refs/heads/main.tar.gz -O /tmp/repo.tar.gz && \
                tar -xzf /tmp/repo.tar.gz --strip-components=1 && \
                rm /tmp/repo.tar.gz && \
                echo "Repository downloaded and extracted successfully"
              elif command -v curl &> /dev/null; then
                curl -sL https://github.com/harmonic-society/refine-jewelry-reform/archive/refs/heads/main.tar.gz -o /tmp/repo.tar.gz && \
                tar -xzf /tmp/repo.tar.gz --strip-components=1 && \
                rm /tmp/repo.tar.gz && \
                echo "Repository downloaded and extracted successfully"
              else
                echo "Error: Neither wget nor curl is available"
                exit 1
              fi
              
              # Gitリポジトリとして初期化
              git init
              git remote add origin https://github.com/harmonic-society/refine-jewelry-reform.git
              git add .
              git commit -m "Initial deployment from GitHub archive"
              git branch -M main
            else
              echo "Pulling latest changes..."
              # 既存のリポジトリがある場合は、fetchとresetで強制更新
              git fetch https://github.com/harmonic-society/refine-jewelry-reform.git main:refs/remotes/origin/main
              git reset --hard origin/main
            fi
            
            echo "Deployed at $(date)"
          EOF
